FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"aWQ6IDI5NGYxNzJlLTI5MmMtNGI4ZC05MjQ5LTQ0NzYzMGI2NzcyZApuYW1lOiBzMmktZXhhbXBs\
ZS1hcGIKaW1hZ2U6IGpraWcvczJpLWV4YW1wbGUtYXBiCmRlc2NyaXB0aW9uOiBUaGlzIGlzIGEg\
c2FtcGxlIEFuc2libGUgUGxheWJvb2sgQnVuZGxlIChBUEIpIHRvIGJlIHVzZWQgZm9yIHRoZSAn\
czJpLWFwYicgYnVpbGRlcgpiaW5kYWJsZTogRmFsc2UKYXN5bmM6IG9wdGlvbmFsCm1ldGFkYXRh\
OgogIGltYWdlVXJsOiBodHRwczovL3VwbG9hZC53aWtpbWVkaWEub3JnL3dpa2lwZWRpYS9jb21t\
b25zL3RodW1iL2MvYzUvTmdpbnhfbG9nby5zdmcvMzIwcHgtTmdpbnhfbG9nby5zdmcucG5nCiAg\
ZGVwZW5kZW5jaWVzOiBbJ2RvY2tlci5pby9uZ2lueDpsYXRlc3QnXQoKcGFyYW1ldGVyczogW10K\
IyAgLSB0ZXN0X3BhcmFtZXRlcjoKIyAgICAgIGRlZmF1bHQ6IHRlc3RfcGFyYW1ldGVyCiMgICAg\
ICB0eXBlOiBzdHJpbmcKIyAgICAgIHRpdGxlOiBUZXN0IFBhcmFtZXRlcgogIApyZXF1aXJlZDog\
W10KIyAgLSB0ZXN0X3BhcmFtZXRlcgo="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
USER apb
